apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: virtual-argocds
spec:
  destination:
    namespace: crossplane-system
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
      include: '*.yaml'
    repoURL: https://github.com/freddieentity/multi-tenant-crossplane-vcluster.git
    targetRevision: HEAD
    path: virtualargocds
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true